<a href="https://colab.research.google.com/github/urness/CS167Fall22Code/blob/main/Day05_Notes_kNN_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 5 Notes: k Nearest Neighbors
The following code includes the steps necessary to build a k nearest neighbors model. We'll go through each step, and then I'll ask you to pull these steps together into a function that you can pass a new observation of a flower in to and it will output the species the model predicts that flower is.

In [31]:
import pandas
from google.colab import drive
drive.mount('/content/drive')
#go through authentication step

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
#import the data and take a look at it
iris_data = pandas.read_csv('/content/drive/MyDrive/CS167Spring22/datasets/irisData.csv')
iris_data.head()

   sepal length  sepal width  petal length  petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [33]:
iris_data['petal width'].mean() #get the average of a column

1.1986666666666668

In [34]:
# Calculate the distance
import numpy
#adding a new column
iris_data['distance_to_new'] = numpy.sqrt(
    (5.1-iris_data['petal length'])**2
    +(7.2-iris_data['sepal length'])**2
    +(1.5-iris_data['petal width'])**2
    +(2.5-iris_data['sepal width'])**2)
iris_data

,sepal length,sepal width,petal length,petal width,species,distance_to_new
0,5.1,3.5,1.4,0.2,Iris-setosa,4.559605
1,4.9,3.0,1.4,0.2,Iris-setosa,4.573839
2,4.7,3.2,1.3,0.2,Iris-setosa,4.782259
3,4.6,3.1,1.5,0.2,Iris-setosa,4.665833
4,5.0,3.6,1.4,0.2,Iris-setosa,4.629255
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,1.072381
146,6.3,2.5,5.0,1.9,Iris-virginica,0.989949
147,6.5,3.0,5.2,2.0,Iris-virginica,1.000000
148,6.2,3.4,5.4,2.3,Iris-virginica,1.593738
149,5.9,3.0,5.1,1.8,Iris-virginica,1.424781

In [35]:
# Sort the data and display it
sorted_data = iris_data.sort_values(['distance_to_new']) 
sorted_data #display it

,sepal length,sepal width,petal length,petal width,species,distance_to_new
76,6.8,2.8,4.8,1.4,Iris-versicolor,0.591608
52,6.9,3.1,4.9,1.5,Iris-versicolor,0.700000
77,6.7,3.0,5.0,1.7,Iris-versicolor,0.741620
50,7.0,3.2,4.7,1.4,Iris-versicolor,0.836660
129,7.2,3.0,5.8,1.6,Iris-virginica,0.866025
...,...,...,...,...,...,...
8,4.4,2.9,1.4,0.2,Iris-setosa,4.835287
38,4.4,3.0,1.3,0.2,Iris-setosa,4.921382
42,4.4,3.2,1.3,0.2,Iris-setosa,4.945705
22,4.6,3.6,1.0,0.2,Iris-setosa,5.144900
13,4.3,3.0,1.1,0.1,Iris-setosa,5.159457

In [41]:
# give the top 5 closest neighbors
sorted_data.iloc[0:5]

,sepal length,sepal width,petal length,petal width,species,distance_to_new
76,6.8,2.8,4.8,1.4,Iris-versicolor,0.591608
52,6.9,3.1,4.9,1.5,Iris-versicolor,0.700000
77,6.7,3.0,5.0,1.7,Iris-versicolor,0.741620
50,7.0,3.2,4.7,1.4,Iris-versicolor,0.836660
129,7.2,3.0,5.8,1.6,Iris-virginica,0.866025

In [42]:
# give the most commonly occuring species of the 5 closest neighbors
sorted_data.iloc[0:5]['species'].mode()
#sorted_data.iloc[0:5]['species'].mode()[0] #return just the string

0    Iris-versicolor
dtype: object

## Exercise:
Now it's your turn. Use the code snippets from above to build out a kNN function that takes in `specimen`, `data`, and `k` and ouputs the prediction.

In [43]:
import numpy
def knn(specimen, training_data, k):
  # your code here
  data_copy = training_data.copy()
  data_copy['distance_to_new'] = numpy.sqrt(
    (specimen['petal length']-data_copy['petal length'])**2
    +(specimen['sepal length']-data_copy['sepal length'])**2
    +(specimen['petal width']-data_copy['petal width'])**2
    +(specimen['sepal width']-data_copy['sepal width'])**2)
  sorted_data = data_copy.sort_values(['distance_to_new']) 
  top_k = sorted_data.iloc[0:k]
  return top_k['species'].mode()[0]

In [46]:
# Use the code below to build a dictionary of values and test your new function:
iris = {}
iris['petal length'] = 5.1
iris['sepal length'] = 7.2
iris['petal width'] = 1.5
iris['sepal width'] = 2.5
# 5-NN 
print(knn(iris,iris_data,5))

Iris-versicolor

## Exercise #2:
Now it's your turn. Use the code snippets from above to build out a *weighted* kNN function that takes in `specimen`, `data`, and `k` and ouputs the prediction.

In [50]:
import numpy

# weighted kNN
def w_knn(specimen, data, k):
  # calculate the distance
  data_copy = data.copy()
  data_copy['distance_to_new'] = numpy.sqrt(
    (specimen['petal length']-data['petal length'])**2
    +(specimen['sepal length']-data['sepal length'])**2
    +(specimen['petal width']-data['petal width'])**2
    +(specimen['sepal width']-data['sepal width'])**2)
  
  # calculate the weights (remember, the weights are 1/d^2)
  data_copy['weights'] = 1/(data_copy['distance_to_new']**2)

  # find the closest k
  sorted_data = data_copy.sort_values(['weights'], ascending = False) 
  top_k = sorted_data.iloc[0:k]

  # use groupby to sum the weights of each species in the closest k
  sum_of_weights_per_species = top_k.groupby(['species'])['weights'].sum()

  sorted = sum_of_weights_per_species.sort_values(ascending=False)
  return sorted.keys()[0]
  # return the class that has the larger sum of weights

In [51]:
iris = {}
iris['petal length'] = 5.1
iris['sepal length'] = 7.2
iris['petal width'] = 1.5
iris['sepal width'] = 2.5
# 5-NN 
print(w_knn(iris,iris_data,5))

Iris-versicolor